import type { Metadata } from 'next';
export const metadata: Metadata={title:'Dein LOVINU-Plan | LOVINU',description:'Der LOVINU-Plan verbindet medizinische Erkenntnisse mit deinen Zielen und macht daraus einen klaren Weg.'};
const steps=['Kennenlernen','Hinschauen','Verstehen','Planen','Handeln','Weitergehen'];
export default function Plan(){return <><Header/><main className="subPage moodDP">
<section className="dpHero"><div><span className="eyebrow">DER LOVINU-PLAN</span><h1>Dein persönlicher<br/>Gesundheitsplan.</h1><p className="lead">Deine Gesundheit ist persönlich. Dein Plan ist es auch.</p><p>Der LOVINU-Plan verbindet medizinische Erkenntnisse mit deinen Zielen und macht daraus einen klaren Weg.</p><a className="pill" href="#contact">LOVINU kennenlernen →</a></div><div className="dpHeroPhoto" role="img" aria-label="Mann als Bildmotiv für den persönlichen Gesundheitsplan"></div><aside><span>DEIN ZIEL</span><blockquote>„Ich möchte wieder genug Kondition haben, um mit meiner Frau lange Wanderungen zu machen.“</blockquote></aside></section>
<section className="dpSteps"><h2>Schritt für Schritt zu deinem Plan.</h2><p>Vom ersten, unverbindlichen Kennenlernen bis zur langfristigen Begleitung. Klar aufgebaut, verständlich erklärt und auf dich abgestimmt.</p><div className="steps moodSteps">{steps.map(h=><div className="step" key={h}><b>{h}</b></div>)}</div></section>
<section className="dpFeature"><div><span className="eyebrow">HINSCHAUEN UND VERSTEHEN</span><h2>Deine Gesundheit.<br/>Heute und morgen.</h2><p>Wir schauen genau hin. Aus Anamnese, Untersuchung und ausgewählten Diagnostik entsteht ein verständliches Bild deiner aktuellen Gesundheit.</p><p>Du siehst, was bereits gut ist, wo Potenziale liegen und welche Themen für dich wirklich relevant sind.</p><a className="pill" href="/was-wir-tun">Wie wir hinschauen →</a></div><div className="healthCard"><span>DEIN GESUNDHEITSBILD</span><div className="score78">78<small>von 100</small></div><ul><li>Herz-Kreislauf <b>72</b></li><li>Stoffwechsel <b>85</b></li><li>Hormonbalance <b>75</b></li><li>Regeneration <b>82</b></li></ul></div></section>
<section className="dpPrior"><div><span className="eyebrow">PLANEN</span><h2>Drei Prioritäten<br/>für mehr gute Jahre.</h2><p>Nicht alles gleichzeitig. Wir definieren die Themen, die für dich den größten Unterschied machen können.</p></div><aside className="wish"><span>DEIN WUNSCHBILD</span><p>„Ich möchte wieder genug Kondition haben, um mit meiner Frau lange Wanderungen zu machen.“</p></aside><div className="priorityGrid"><article><span>01</span><b>Herz-Kreislauf stärken</b><p>Für ein aktives, belastbares Leben.</p></article><article><span>02</span><b>Besser schlafen & regenerieren</b><p>Für mehr Energie im Alltag.</p></article><article><span>03</span><b>Stoffwechsel optimieren</b><p>Für langfristige Gesundheit.</p></article></div></section>
<section className="dpJourney"><span className="eyebrow">HANDELN UND WEITERGEHEN</span><h2>Dein Weg zu mehr guten Jahren.</h2><p>Aus deinen Prioritäten entsteht ein konkreter Plan. Medizinische, therapeutische und präventive Maßnahmen greifen dabei sinnvoll ineinander.</p><div className="journeyMonths">{['Monat 1\nStarten','Monat 2\nUmsetzen','Monat 3\nDranbleiben','Monat 4\nAnpassen','Monat 5\nVertiefen','Monat 6\nBilanzieren'].map(x=><b key={x}>{x.split('\n').map((t,i)=><span key={t}>{t}</span>)}</b>)}</div><div className="journeyRows">{['Medizin & Diagnostik','Ernährung','Bewegung','Regeneration','Supplementierung','Ärztliche Begleitung'].map(x=><div key={x}><b>{x}</b><span>individuell abgestimmt · begleitet · überprüft · angepasst</span></div>)}</div></section>
<section className="principle moodPrinciple"><blockquote>Nicht jeder braucht dasselbe.<br/><strong>Du bekommst das, was für dich sinnvoll ist.</strong></blockquote><div><p>Der LOVINU-Plan ist kein starres Programm. Er entwickelt sich mit dir – auf Basis deiner Ergebnisse, deiner Ziele und dessen, was sich im Verlauf zeigt.</p><a className="pill" href="#contact">LOVINU kennenlernen →</a></div></section>
</main><Footer/></>}
function Header(){return <header className="siteHeader"><a className="brand" href="/"><img src="/brand/lovinu-logo.svg" alt="LOVINU"/></a><nav><a href="/">Home</a><a href="/personal-longevity">Personal Longevity</a><a href="/was-wir-tun">Was wir tun</a><a className="active" href="/dein-plan">Dein LOVINU-Plan</a><a href="/ueber-lovinu">Über LOVINU</a><a href="/wissen">Wissen</a><a href="/kontakt">Kontakt</a></nav><a className="pill headerCta" href="#contact">Termin vereinbaren →</a></header>}
function Footer(){return <footer id="contact"><img className="footerLogo" src="/brand/lovinu-logo-white.png" alt="LOVINU"/><span>Lebensfreude durch Gesundheit.</span><div className="legal"><a href="#">Impressum</a><a href="#">Datenschutz</a><a href="/kontakt">Kontakt</a></div><div className="footerClaim"><img src="/brand/lovinu-heart-white.png" alt=""/> <b>Länger gut leben.</b></div></footer>}
