import type { Metadata } from 'next';
export const metadata: Metadata={title:'Personal Longevity | LOVINU',description:'Personal Longevity bei LOVINU: Gesundheit aktiv verstehen, gezielt stärken und die Grundlage für mehr gesunde Lebensjahre schaffen.'};
const four=[
 ['/images/mood/icons/verstehen.png','Verstehen','Wir analysieren deine individuelle Situation auf Basis modernster Diagnostik.'],
 ['/images/mood/icons/handeln.png','Handeln','Du erhältst konkrete Empfehlungen für Ernährung, Bewegung, Regeneration und Mikronährstoffe.'],
 ['/images/mood/icons/dranbleiben.png','Dranbleiben','Wir begleiten dich mit Wissen, Tools und persönlicher Betreuung auf deinem Weg.'],
 ['/images/mood/icons/mehr.png','Mehr vom Leben','Für mehr Energie, Klarheit und gesunde Jahre – heute und in Zukunft.']
];
const practical=[
 ['Wir beginnen mit einem','verständlichen Gespräch auf Augenhöhe','über deine Lebensumstände, inkl. einer detaillierten Auswertung deiner Laborwerte und Gesundheitsdaten.'],
 ['Es folgen','umsetzbare Empfehlungen','von individuell auf dich abgestimmten Maßnahmen für deinen Alltag.'],
 ['Fällt dir mal etwas schwer:','You never walk alone!','Wir begleiten dich mit unserem Wissen und kontinuierlicher Unterstützung.'],
 ['Für dein möglichst aktives, erfülltes Leben haben wir','ein gemeinsames Ziel:','mehr gesunde Jahre.']
];
export default function PersonalLongevity(){return <><Header/><main className="subPage moodPL">
<section className="plV5Hero"><div className="plV5HeroCopy"><h1>Wie möchtest<br/>du leben, während<br/>du älter wirst?</h1><p>Mehr gesunde Jahre für das,<br/>was dir wirklich wichtig ist.</p><a className="pill" href="#personal">Deinen Weg entdecken →</a></div></section>
<section className="moodCenter plV5Intro" id="personal"><span className="eyebrow">PERSONAL LONGEVITY</span><h2>Heute mehr für morgen tun.</h2><p>Personal Longevity bedeutet, deine Gesundheit aktiv zu verstehen, gezielt zu stärken und so die Grundlage für mehr gesunde Lebensjahre zu schaffen – individuell, wissenschaftlich fundiert und alltagstauglich.</p><div className="moodFour plV5Four">{four.map(([i,h,p])=><article key={h}><img src={i} alt=""/><h3>{h}</h3><p>{p}</p></article>)}</div></section>
<section className="moodSplit plV5Split"><div><span className="eyebrow">DER BLICK VORAUS</span><h2>Gesundheit beginnt<br/>nicht erst, wenn<br/>etwas fehlt.</h2><p>Mit einer umfassenden Analyse deiner individuellen Gesundheitsdaten – z. B. aus einem detaillierten Blutbild – erkennen wir, was dein Körper heute schon braucht, um morgen stark zu sein.</p><a className="pill" href="/was-wir-tun">Mehr zur Diagnostik →</a></div><img src="/images/mood/personal-diagnostic-clean.png" alt="Medizinische Diagnostik"/></section>
<section className="moodCenter moodPlan plV5Plan"><span className="eyebrow">DEIN INDIVIDUELLER PLAN</span><h2>Klar. Umsetzbar. Auf dich abgestimmt.</h2><p>Aus deinen Ergebnissen entwickeln wir einen persönlichen Plan – keine Standardlösung,<br className="desktopOnly"/> sondern konkrete Empfehlungen, die zu deinem Leben passen.</p><div className="moodFour practicalFour">{practical.map(([lead,h,p])=><article key={h}><p className="practicalLead">{lead}</p><h3>{h}</h3><p>{p}</p></article>)}</div><a className="pill" href="/dein-plan">Jetzt deinen Plan starten →</a></section>
<section className="moodVision plV5Vision"><div><span className="eyebrow">MEHR ALS EIN ZIEL</span><h2>Es geht nicht nur um ein längeres Leben.<br/>Sondern um ein besseres.</h2><p>Wir glauben an eine Zukunft, in der du die Freiheit hast, deine Zeit so zu nutzen, wie du es dir wünschst – mit Energie, Gesundheit und Lebensfreude.</p><a className="pill" href="#contact">Unsere Vision →</a></div><img src="/images/mood/personal-future-clean.png" alt="Aktiv und selbstbestimmt leben"/></section>
<section className="moodTestimonial plV5Testimonial"><img src="/images/mood/markus.png" alt="Markus"/><div><span className="eyebrow">STIMMEN AUS DER COMMUNITY</span><blockquote className="quoteMarks">Ich habe durch LOVINU zum ersten Mal wirklich verstanden,<br className="desktopOnly"/> wo ich stehe – und was ich konkret tun kann. Das gibt mir ein<br className="desktopOnly"/> gutes Gefühl für die Zukunft.</blockquote><p><strong>Markus, 52</strong><br/>Teilnehmer Personal Longevity</p></div><div className="testimonialArrows">‹ &nbsp; ›</div></section>
<section className="moodCta" id="contact"><div><span className="eyebrow">BEREIT FÜR MEHR GESUNDE JAHRE?</span><h2>Starte jetzt mit deinem persönlichen Longevity-Plan.</h2></div><a className="pill whitePill" href="mailto:kontakt@lovinu.de">Jetzt loslegen →</a></section>
</main><Footer/></>}
function Header(){return <header className="siteHeader"><a className="brand" href="/"><img src="/brand/lovinu-logo.svg" alt="LOVINU"/></a><nav><a href="/">Home</a><a className="active" href="/personal-longevity">Personal Longevity</a><a href="/was-wir-tun">Was wir tun</a><a href="/dein-plan">Dein Plan</a><a href="/ueber-lovinu">Über LOVINU</a><a href="#">Wissen</a><a href="#contact">Kontakt</a></nav><a className="pill headerCta" href="#contact">Termin vereinbaren →</a></header>}
function Footer(){return <footer><img className="footerLogo" src="/brand/lovinu-logo-white.png" alt="LOVINU"/><span>Lebensfreude durch Gesundheit.</span><div className="legal"><a href="#">Impressum</a><a href="#">Datenschutz</a><a href="#contact">Kontakt</a></div><div className="footerClaim"><img src="/brand/lovinu-heart-white.png" alt=""/> <b>Länger gut leben.</b></div></footer>}
